In [1]:
import pandas as pd
df = pd.read_csv ('HSR Metro SG_exit (Pin Chi) - Copy of THSR_exit.csv')
if df['Stationname En'][0] == 'Nangang' :
    print(df['Stationname En'][0])
len(df['Stationname En'])
df.head()

Nangang

,Stationid,Stationname En,Exitid,short name,Exitposition Positionlon,Exitposition Positionlat,layer,stationid,exitid,groovy code,Unnamed: 10,"exit """
0,990,Nangang,North Exit,NorthExit,121.60706,25.05348,NaN,TaiwanStation_NanGangNangang,TaiwanStation_NanGangNangang_ENorthExit,"exit ""TaiwanStation_NanGangNangang_ENorthExit""...",NaN,""" with { short_name """
1,990,Nangang,South Exit,SouthExit,121.60641,25.05283,NaN,TaiwanStation_NanGangNangang,TaiwanStation_NanGangNangang_ESouthExit,"exit ""TaiwanStation_NanGangNangang_ESouthExit""...",NaN,""" coords { lat"
2,1000,Taipei,East 1,East1,121.51793,25.04811,NaN,TaiwanStation_TaiBeiCheZhanTaipeiMainStation,TaiwanStation_TaiBeiCheZhanTaipeiMainStation_E...,"exit ""TaiwanStation_TaiBeiCheZhanTaipeiMainSta...",NaN,; lon
3,1000,Taipei,East 2,East2,121.51784,25.04771,NaN,TaiwanStation_TaiBeiCheZhanTaipeiMainStation,TaiwanStation_TaiBeiCheZhanTaipeiMainStation_E...,"exit ""TaiwanStation_TaiBeiCheZhanTaipeiMainSta...",NaN,} layer
4,1000,Taipei,East 3,East3,121.51775,25.04731,NaN,TaiwanStation_TaiBeiCheZhanTaipeiMainStation,TaiwanStation_TaiBeiCheZhanTaipeiMainStation_E...,"exit ""TaiwanStation_TaiBeiCheZhanTaipeiMainSta...",NaN,}

In [5]:
class exitprint:
    def __init__(self, station_inf):
        self.short_name = station_inf[0]
        self.lon = station_inf[1]
        self.lat = station_inf[2]
        self.exitid = station_inf[3]
    def printGroovyCode(self):
        for i in range(len(self.exitid)):
            groovyCode = "exit \"" + self.exitid[i] + "\" with {\n" + \
                         "    short_name \"" + self.short_name[i] + "\"\n" + \
                         "    coords { lat " + str(self.lon[i]) + "; lon " + str(self.lat[0]) + " }\n" + \
                         "    layer 0\n}"
            print(groovyCode)

In [6]:
# input the station name and output the results
stationName = input('Enter the stationüëç :')
station_inf = [[],[],[],[]] # shortname,lon,lat,exitid
for i in range(len(df['Stationname En'])) :
    if df['Stationname En'][i] == stationName :
        station_inf[0].append(df['short name'][i])
        station_inf[1].append(df['Exitposition Positionlon'][i])
        station_inf[2].append(df['Exitposition Positionlat'][i])
        station_inf[3].append(df['exitid'][i])

Enter the stationüëç :Banqiao

In [7]:
 # Example output format:
 # exit "TaiwanStation_NanGangNangang_E42781" with {
 #    short_name "1"
 #    coords { lat 25.051816; lon 121.606523 }
 #    layer 0
 # }
test = exitprint(station_inf)
test.printGroovyCode()

exit "TaiwanStation_BanQiaoBanqiao_EEast1" with {
    short_name "East1"
    coords { lat 121.46382; lon 25.01484 }
    layer 0
}
exit "TaiwanStation_BanQiaoBanqiao_EEast2" with {
    short_name "East2"
    coords { lat 121.46404; lon 25.01484 }
    layer 0
}
exit "TaiwanStation_BanQiaoBanqiao_ENorth1" with {
    short_name "North1"
    coords { lat 121.46367; lon 25.01484 }
    layer 0
}
exit "TaiwanStation_BanQiaoBanqiao_ENorth1A" with {
    short_name "North1A"
    coords { lat 121.46352; lon 25.01484 }
    layer 0
}
exit "TaiwanStation_BanQiaoBanqiao_ENorth2" with {
    short_name "North2"
    coords { lat 121.46338; lon 25.01484 }
    layer 0
}
exit "TaiwanStation_BanQiaoBanqiao_ENorth2A" with {
    short_name "North2A"
    coords { lat 121.46322; lon 25.01484 }
    layer 0
}
exit "TaiwanStation_BanQiaoBanqiao_ENorth3" with {
    short_name "North3"
    coords { lat 121.46305; lon 25.01484 }
    layer 0
}
exit "TaiwanStation_BanQiaoBanqiao_ESouth1" with {
    short_name "South1"
    coords { lat 121.46397; lon 25.01484 }
    layer 0
}
exit "TaiwanStation_BanQiaoBanqiao_ESouth2" with {
    short_name "South2"
    coords { lat 121.46377; lon 25.01484 }
    layer 0
}
exit "TaiwanStation_BanQiaoBanqiao_ESouth3" with {
    short_name "South3"
    coords { lat 121.46351; lon 25.01484 }
    layer 0
}
exit "TaiwanStation_BanQiaoBanqiao_EWest" with {
    short_name "West"
    coords { lat 121.46321; lon 25.01484 }
    layer 0
}